name: Piso Exp

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04 # Mantemos a versão estável

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Não precisamos mais desabilitar o IPv6
      
      - name: Restaurar hxh.json a partir do segredo
        run: |
          echo "$GCP_JSON_BASE64" | base64 -d > hxh.json
        shell: bash
        env:
          GCP_JSON_BASE64: ${{ secrets.GCP_JSON_BASE64 }}

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # ==========================================================
      # NOVO STEP USANDO A ACTION OFICIAL
      # (Substitui o 'playwright install')
      # ==========================================================
      - name: Instalar Navegador Playwright
        uses: microsoft/playwright-github-action@v1
        with:
          # Instala somente o chromium e suas dependências
          install-browsers: chromium 

      - name: Executar o script
        run: xvfb-run python main-mg2.py
        env:
          OPS_ID: ${{ secrets.OPS_ID }}
          OPS_SENHA: ${{ secrets.OPS_SENHA }}
